### ISSUE TITLE
Eventstorage

### ISSUE THREAD

**Issue by ghost** [isoos/message_hub#1]
I am really impressed with this and PWA.

Is it envisaged that the hub would be able to be extended with persistence , so that when a long running worker gets killed by the mobile OS shutting down the app to recover ram that the event can be replayed back on the mobile is restarting the app.

**Comment by isoos** [comment]
@gedw99: At this point I don't think that this library would be anything more than handling "remote" APIs calls through a simplified local API. I believe that it should be easy to build other functions on top of it, but it would be helpful for me if you could explain what you are looking for here, explaining a bit more in details.

**Comment by ghost** [comment]
Ok so he bigger picture is to build a type of cqrs setup using service workers and web workers.
Hopefully you know cqrs. If not there is already one for dart called Harvest that is very well done. Just Google for it.

So the web workers do off GUI thread process and communicate via message passing and so they are just like a microservice and talk to the main GUI thread by the message hub.

I am writing the web workers in golang and compile to Js or WASM. Each recieves event command from the message hub queue and does computation and updates it own indexdb database. The data is essentially an aggregation if a materialised view ( as a DB admin calls it) I will build various indexers in golang with it so you can do high quality indexing and hence queries.

So a query from the dart GUI thread is passed into the hub and is returned. These queries are described by graphql which is then able to query each data store inside the web worker.

Why built it this way ?
Offline first
Move the golang to server, flutter or web with no dependency other than the message passing.
No need for a Reflux or Reflux pattern in the dart code. The basic cqrs architecture replaces reflux and has the big advantage of working anywhere.

There is a dart package called "PWA" which also helps this.

You can catch me via Gmail using my GitHub user name if you want to discuss further.

**Comment by ghost** [comment]
https://pub.dartlang.org/packages/pwa

https://pub.dartlang.org/packages/harvest
A bit old but can get working with strong mode

**Comment by isoos** [comment]
@gedw99: what would you expect from this library?

**Comment by ghost** [comment]
nothing. i am just shooting an idea of how to extend and use the library
